from yacs.config import CfgNode as CN

_C = CN()

_C.TRAIN = CN()
_C.TRAIN.OUTPUT_DIR = "output"
_C.TRAIN.LEARNING_RATE = 1e-3
_C.TRAIN.WEIGHT_DECAY = 0
_C.TRAIN.LOCAL_RANK = -1
_C.TRAIN.TRAIN_BATCH_SIZE = 32
_C.TRAIN.EVAL_BATCH_SIZE = 32
_C.TRAIN.NUM_STEPS = 30000
_C.TRAIN.WARMUP_STEPS = 500
_C.TRAIN.EVAL_EVERY = 100
_C.TRAIN.SEED = 42
_C.TRAIN.GRADIENT_ACCUMULATION_STEPS = 1


_C.MODEL = CN()
_C.MODEL.PRETRAIN_DIR = "./resnet50.pth"
_C.MODEL.IMAGE_SIZE = 224
_C.MODEL.CALSS_NUMBER = 38
_C.MODEL.D_MODEL = 512
_C.MODEL.HIDDEN_DIM = 512
_C.MODEL.DROPOUT = 0.1
_C.MODEL.MAX_GRAD_NORM = 1.0
_C.MODEL.NHEADS = 4
_C.MODEL.DIM_FEEDFORWARD = 2048
_C.MODEL.ENC_LAYERS = 2
_C.MODEL.DEC_LAYERS = 2
_C.MODEL.PRE_NORM = True
_C.MODEL.SRC_LEN = 4
_C.MODEL.POS_EMB_TYPE = 'v4'

